2022/11/22 20:42:11 [error] 8#8: *2 FastCGI sent in stderr: "PHP message: 2022-11-22T21:42:11+01:00 [critical] Uncaught Exception: Unable to write in the "logs" directory (/var/www/docsarchive/var/logs)" while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:8089"
2022/12/01 16:03:31 [error] 8#8: *6 FastCGI sent in stderr: "PHP message: 2022-12-01T17:03:31+01:00 [critical] Uncaught Exception: Unrecognized option "firewalls" under "security.firewalls.main". Available options are "access_denied_handler", "access_denied_url", "context", "custom_authenticators", "entry_point", "form_login", "form_login_ldap", "host", "http_basic", "http_basic_ldap", "json_login", "json_login_ldap", "lazy", "login_link", "" while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:8089"
2022/12/01 16:03:31 [error] 8#8: *6 FastCGI sent in stderr: "login_throttling", "logout", "methods", "pattern", "provider", "remember_me", "remote_user", "request_matcher", "required_badges", "security", "stateless", "switch_user", "user_checker", "x509"" while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:8089"
2022/12/01 16:28:58 [crit] 7#7: *3 open() "/var/lib/nginx/tmp/fastcgi/1/00/0000000001" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /login HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099"
2022/12/01 16:29:02 [error] 7#7: *3 FastCGI sent in stderr: "PHP message: 2022-12-01T17:29:02+01:00 [critical] Uncaught Exception: The configuration key "Symfony\Component\Ldap\Adapter\ExtLdap\Adapter" is unsupported for definition "Symfony\Component\Ldap\Ldap" in "/var/www/docsarchive/config/services.yaml". Allowed configuration keys are "alias", "parent", "class", "shared", "synthetic", "lazy", "public", "abstract", "deprecated", "factory", "file", "arguments", "properties", "configurator", "calls", "tags", "decorates", "decoration_inner_name", "decoration_priority", "decoration_on_invalid", "autowire", "autoconfigure", "bind" in /var/www/docsarchive/config/services.yaml (which is being imported from "/var/www/docsarchive/src/Kernel.php")" while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /login HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099"
2022/12/01 16:34:04 [error] 7#7: *15 FastCGI sent in stderr: "PHP message: 2022-12-01T17:34:04+01:00 [critical] Uncaught Exception: Because you have multiple authenticators in firewall "main", you need to set the "entry_point" key to one of your authenticators ("form_login", "form_login_ldap") or a service ID implementing "Symfony\Component\Security\Http\EntryPoint\AuthenticationEntryPointInterface". The "entry_point" determines what should happen (e.g. redirect to "/login") when an anonymous user tries to access a protected page" while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /login HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099"
2022/12/02 20:17:29 [crit] 8#8: *31 open() "/var/lib/nginx/tmp/fastcgi/1/00/0000000001" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "POST /login HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/login"
2022/12/02 20:17:59 [crit] 8#8: *31 open() "/var/lib/nginx/tmp/fastcgi/2/00/0000000002" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "POST /login HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/login"
2022/12/02 20:42:11 [crit] 7#7: *16 open() "/var/lib/nginx/tmp/fastcgi/1/00/0000000001" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /login HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/login"
2022/12/02 20:42:17 [error] 7#7: *16 FastCGI sent in stderr: "PHP message: 2022-12-02T21:42:17+01:00 [critical] Uncaught Exception: Unrecognized option "test" under "security.firewalls.main.form_login". Available options are "always_use_default_target_path", "check_path", "csrf_parameter", "csrf_token_generator", "csrf_token_id", "default_target_path", "enable_csrf", "failure_forward", "failure_handler", "failure_path", "failure_path_parameter", "form_only", "login_path", "password_parameter", "post_only", "provider", "remember_me", "require_previous_session", "success_handler", "target_path_parameter", "use_forward", "use_referer", "username_parameter"" while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /login HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099"
2022/12/02 20:45:30 [error] 7#7: *16 FastCGI sent in stderr: "PHP message: 2022-12-02T21:45:30+01:00 [critical] Uncaught Exception: Unrecognized option "test" under "security.providers.app_user_provider.entity". Available options are "cla" while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /login HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099"
2022/12/02 20:45:30 [error] 7#7: *16 FastCGI sent in stderr: "ss", "manager_name", "property"" while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /login HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099"
2022/12/02 20:48:07 [error] 7#7: *16 FastCGI sent in stderr: "PHP mess" while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /login HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099"
2022/12/02 20:48:07 [error] 7#7: *16 FastCGI sent in stderr: "age: 2022-12-02T21:48:07+01:00 [critical] Uncaught Exception: Unrecognized option "anonymous" under "security.firewalls.main". Available options are "access_denied_handler", "access_denied_url", "context", "custom_authenticators", "entry_point", "form_login", "form_login_ldap", "host", "http_basic", "http_basic_ldap", "json_login", "json_login_ldap", "lazy", "login_link", "login_throttling", "logout", "methods", "pattern", "provider", "remember_me", "remote_user", "request_matcher", "required_badges", "security", "stateless", "switch_user", "user_checker", "x509"" while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /login HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099"
2022/12/02 20:58:04 [error] 7#7: *65 FastCGI sent in stderr: "PHP mess" while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /login HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099"
2022/12/02 20:58:04 [error] 7#7: *65 FastCGI sent in stderr: "age: 2022-12-02T21:58:04+01:00 [critical] Uncaught Exception: Unrecognized option "anonymous" under "security.firewalls.main". Available options are "access_denied_handler", "access_denied_url", "context", "custom_authenticators", "entry_point", "form_login", "form_login_ldap", "host", "http_basic", "http_basic_ldap", "json_login", "json_login_ldap", "lazy", "login_link", "login_throttling", "logout", "methods", "pattern", "provider", "remember_me", "remote_user", "request_matcher", "required_badges", "security", "stateless", "switch_user", "user_checker", "x509"" while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /login HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099"
2022/12/02 21:02:05 [error] 7#7: *65 FastCGI sent in stderr: "PHP message: 2022-12-02T22:02:05+01:00 [critical] Uncaught Exception: Because you have multiple authenticators in firewall "main", you need to set the "entry_point" key to one of your authenticators ("App\Security\LdapAuthenticator", "form_login") or a service ID implementing "Symfony\Component\Security\Http\EntryPoint\AuthenticationEntryPointInterface". The "entry_point" determines what should happen (e.g. redirect to "/login") when an anonymous user tries to access a protected page" while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /login HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099"
2022/12/02 21:03:49 [error] 7#7: *65 FastCGI sent in stderr: "PHP message: 2022-12-02T22:03:49+01:00 [critical] Uncaught Exception: Because you have multiple authenticators in firewall "main", you need to set the "entry_point" key to one of your authenticators ("App\Security\LdapAuthenticator", "form_login") or a service ID implementing "Symfony\Component\Security\Http\EntryPoint\AuthenticationEntryPointInterface". The "entry_point" determines what should happen (e.g. redirect to "/login") when an anonymous user tries to access a protected page" while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /login HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099"
2022/12/05 00:06:59 [error] 7#7: *162 FastCGI sent in stderr: "PHP message: 2022-12-05T01:06:59+01:00 [critical] Uncaught Exception: A service definition must be an array or a string starting with "@" but "string" found for service "App\Repository\UserRepositoryInterface" in "/var/www/docsarchive/config/services.yaml". Check your YAML syntax in /var/www/docsarchive/config/services.yaml (which is being imported from "/var/www/docsarchive/src/Kernel.php")" while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099"
2022/12/05 01:05:14 [error] 7#7: *231 FastCGI sent in stderr: "PHP message: 2022-12-05T02:05:14+01:00 [critical] Uncaught Error: syntax error, unexpected token "[", expecting ";" or "{"" while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099"
2022/12/05 01:27:23 [crit] 7#7: *257 open() "/var/lib/nginx/tmp/fastcgi/1/00/0000000001" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099"
2022/12/05 03:27:29 [crit] 7#7: *271 open() "/var/lib/nginx/tmp/fastcgi/2/00/0000000002" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099"
2022/12/05 03:50:29 [crit] 7#7: *281 open() "/var/lib/nginx/tmp/fastcgi/3/00/0000000003" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099"
2022/12/05 03:55:11 [crit] 7#7: *281 open() "/var/lib/nginx/tmp/fastcgi/4/00/0000000004" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099"
2022/12/05 05:54:16 [crit] 7#7: *459 open() "/var/lib/nginx/tmp/fastcgi/5/00/0000000005" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /users HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099"
2022/12/05 13:52:09 [crit] 7#7: *569 open() "/var/lib/nginx/tmp/fastcgi/6/00/0000000006" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /users HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/"
2022/12/06 21:46:25 [crit] 7#7: *2121 open() "/var/lib/nginx/tmp/fastcgi/7/00/0000000007" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "POST /project/add HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/project/add"
2022/12/07 07:59:29 [crit] 7#7: *2406 open() "/var/lib/nginx/tmp/fastcgi/8/00/0000000008" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "POST /project/add HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/project/add"
2022/12/07 08:21:30 [crit] 7#7: *2419 open() "/var/lib/nginx/tmp/fastcgi/9/00/0000000009" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "POST /project/add HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/project/add"
2022/12/07 08:32:29 [error] 7#7: *2454 FastCGI sent in stderr: "PHP message: 2022-12-07T09:32:29+01:00 [critical] Uncaught Exception: The value "yaml" is not allowed for path "framework.validation.email_validation_mode". Permissible values: "html5", "loose", "strict"" while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /project/add HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/"
2022/12/07 08:33:17 [error] 7#7: *2454 FastCGI sent in stderr: "PHP message: 2022-12-07T09:33:17+01:00 [critical] Uncaught Exception: Unrecognized option "App\Entity\" under "framework.validation". Available options are "auto_mapping", "cache", "email_validation_mode", "enable_annotations", "enabled", "mapping", "not_compromised_password", "static_method", "translation_domain"" while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /project/add HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/"
2022/12/07 14:05:49 [crit] 7#7: *2473 open() "/var/lib/nginx/tmp/fastcgi/0/01/0000000010" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/project/add"
2022/12/07 17:39:54 [error] 7#7: *2518 FastCGI sent in stderr: "PHP message: 2022-12-07T18:39:54+01:00 [critical] Uncaught Exception: The value "ds" is not allowed for path "framework.validation.email_validation_mode". Permissible values: "html5", "loose", "strict"" while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /project/add HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/"
2022/12/07 18:37:21 [crit] 7#7: *2587 open() "/var/lib/nginx/tmp/fastcgi/1/01/0000000011" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "POST /project/add HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/project/add"
2022/12/07 19:39:31 [error] 7#7: *2730 FastCGI sent in stderr: "PHP message: 2022-12-07T20:39:31+01:00 [critical] Uncaught Error: syntax error, unexpected variable "$builder"" while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /project/edit/11 HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/"
2022/12/07 19:39:42 [error] 7#7: *2730 FastCGI sent in stderr: "PHP message: 2022-12-07T20:39:42+01:00 [critical] Uncaught Error: syntax error, unexpected variable "$builder"" while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /project/edit/11 HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/"
2022/12/07 21:57:15 [crit] 7#7: *2912 open() "/var/lib/nginx/tmp/fastcgi/2/01/0000000012" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /users HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/"
2022/12/08 11:05:35 [crit] 7#7: *121 open() "/var/lib/nginx/tmp/fastcgi/1/00/0000000001" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /project/3/documents HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/"
2022/12/08 11:11:40 [crit] 7#7: *121 open() "/var/lib/nginx/tmp/fastcgi/2/00/0000000002" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /project/2/documents HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/"
2022/12/09 07:54:59 [crit] 7#7: *1337 open() "/var/lib/nginx/tmp/fastcgi/1/00/0000000001" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/login"
2022/12/09 10:11:58 [crit] 7#7: *1475 open() "/var/lib/nginx/tmp/fastcgi/2/00/0000000002" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /project/2/documents/add HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099"
2022/12/09 10:40:51 [crit] 7#7: *1535 open() "/var/lib/nginx/tmp/fastcgi/3/00/0000000003" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "POST /project/2/documents/add HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/project/2/documents/add"
2022/12/09 10:56:03 [error] 7#7: *1558 FastCGI sent in stderr: "PHP message: 2022-12-09T11:56:03+01:00 [critical] Uncaught Exception: Cannot autowire service "App\Service\UserProvider": argument "$tokenStorage" of method "__construct()" references class "Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage" but no such service exists. Try changing the type-hint to "Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface" instead" while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "POST /project/2/documents/add HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/project/2/documents/add"
2022/12/09 16:06:25 [crit] 7#7: *1635 open() "/var/lib/nginx/tmp/fastcgi/4/00/0000000004" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /project/5/documents/add HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099"
2022/12/09 17:06:43 [crit] 7#7: *1689 open() "/var/lib/nginx/tmp/fastcgi/5/00/0000000005" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "POST /project/4/documents/add HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/project/4/documents/add"
2022/12/09 23:10:37 [crit] 7#7: *1799 open() "/var/lib/nginx/tmp/fastcgi/6/00/0000000006" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /project/3/documents HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/"
2022/12/13 11:27:03 [crit] 7#7: *2406 open() "/var/lib/nginx/tmp/fastcgi/7/00/0000000007" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /project/2/documents HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/documents/edit/10/2"
2022/12/13 11:54:17 [crit] 7#7: *2447 open() "/var/lib/nginx/tmp/fastcgi/8/00/0000000008" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /project/2/documents HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099"
2022/12/15 19:28:43 [crit] 7#7: *177 open() "/var/lib/nginx/tmp/fastcgi/1/00/0000000001" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /project/4/documents HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/"
2022/12/15 19:29:36 [crit] 7#7: *177 open() "/var/lib/nginx/tmp/fastcgi/2/00/0000000002" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /project/4/documents HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/"
2022/12/16 20:29:01 [crit] 7#7: *760 open() "/var/lib/nginx/tmp/fastcgi/3/00/0000000003" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /project/5/documents/add HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/project/5/documents"
2022/12/16 22:10:59 [crit] 7#7: *958 open() "/var/lib/nginx/tmp/fastcgi/4/00/0000000004" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /project/edit/12 HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/"
2022/12/16 22:52:04 [crit] 7#7: *1064 open() "/var/lib/nginx/tmp/fastcgi/5/00/0000000005" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "POST /project/5/documents/add HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/project/5/documents/add"
2022/12/22 16:39:45 [crit] 9#9: *37 open() "/var/lib/nginx/tmp/fastcgi/1/00/0000000001" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/project/5/documents"
2023/01/11 21:16:30 [crit] 7#7: *595 open() "/var/lib/nginx/tmp/fastcgi/2/00/0000000002" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/project/5/documents"
2023/01/11 22:05:24 [crit] 7#7: *722 open() "/var/lib/nginx/tmp/fastcgi/3/00/0000000003" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "POST /download HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/"
2023/01/11 22:12:33 [crit] 7#7: *726 open() "/var/lib/nginx/tmp/fastcgi/4/00/0000000004" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "POST /download HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/"
2023/01/17 22:37:04 [error] 9#9: *1072 FastCGI sent in stderr: "PHP message: 2023-01-17T23:37:04+01:00 [critical] Uncaught Error: syntax error, unexpected variable "$exception"" while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "POST /download HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/project/5/documents"
2023/01/17 23:16:03 [crit] 9#9: *1109 open() "/var/lib/nginx/tmp/fastcgi/1/00/0000000001" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "POST /download HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/"
2023/01/18 21:02:31 [crit] 9#9: *1285 open() "/var/lib/nginx/tmp/fastcgi/2/00/0000000002" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/users"
2023/01/19 14:09:30 [crit] 9#9: *1668 open() "/var/lib/nginx/tmp/fastcgi/3/00/0000000003" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /project/5/documents/add HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099"
2023/02/16 15:45:41 [error] 7#7: *5 FastCGI sent in stderr: "PHP message: 2023-02-16T16:45:41+01:00 [critical] Uncaught Exception: Invalid firewall "main": user provider "ldap" not found" while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /login HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/"
2025/01/09 10:49:07 [crit] 7#7: *1 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/1.1", host: "localhost:8089"
2025/01/09 10:49:07 [crit] 7#7: *1 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8089", referrer: "http://localhost:8089/"
2025/01/09 10:49:25 [crit] 7#7: *1 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/1.1", host: "localhost:8089"
2025/01/13 12:21:00 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:22:41 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:22:43 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:22:45 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:23:28 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:23:47 [crit] 7#7: *8 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/1.1", host: "localhost:8089"
2025/01/13 12:23:55 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:41:04 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:41:06 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:41:07 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:41:07 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:41:46 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:41:47 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:42:31 [crit] 7#7: *16 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "docs.localhost:9099"
2025/01/13 12:42:31 [crit] 7#7: *16 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET /favicon.ico HTTP/2.0", host: "docs.localhost:9099", referrer: "https://docs.localhost:9099/"
2025/01/13 12:42:40 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:42:41 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:43:20 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:43:21 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:43:21 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:43:21 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:43:22 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:43:22 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:43:22 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:43:22 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:43:33 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:43:34 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:43:35 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:43:35 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:43:35 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:43:35 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:43:35 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:43:36 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:44:44 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:44:54 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:45:26 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:45:26 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:45:27 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:45:27 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:45:27 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:45:27 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:45:27 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:45:28 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:47:18 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:47:18 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:47:19 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:47:19 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:47:19 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:47:19 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/13 12:49:02 [crit] 7#7: *2 realpath() "/var/www/docsarchive/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
2025/01/14 13:16:38 [crit] 7#7: *24 open() "/var/lib/nginx/tmp/fastcgi/1/00/0000000001" failed (13: Permission denied) while reading upstream, client: 172.61.0.1, server: dccs.localhost, request: "GET /assets/bundles/sonataadmin/app-OF2Gq-u.js HTTP/2.0", upstream: "fastcgi://172.61.0.2:9004", host: "localhost:9099", referrer: "https://localhost:9099/admin/dashboard"
2025/01/15 09:50:35 [crit] 7#7: *2 realpath() "/var/www/sellingo/public" failed (2: No such file or directory), client: 172.61.0.1, server: dccs.localhost, request: "GET / HTTP/2.0", host: "localhost:9099"
